Changed: Bump gradle to 9.2.1
- After https://github.com/termux/termux-app/pull/3619, this is necessary for building termux-am-library from source in the same Gradle project as termux-app when building all of Termux from source rather than downloading a prebuilt termux-am-library from Maven

Updates:

- Gradle from `7.2` to `9.2.1`

- The [Android Gradle plugin](https://developer.android.com/build/releases/gradle-plugin) from `7.0.3` to `8.13.2` (note that this change requires gradle to be run with java 17)

- Ensure to add a `publishing` block to the `android` block and change the `publications` block to use `from components.default` instead  of `from components.release` or `from components.findByName('release')` to avoid this kind of error in Maven reverse dependencies:

```
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR: /home/tacokoneko/code/termux/termux-generator/termux-apps-main/termux-api/app/src/main/AndroidManifest.xml:72:9-76:20: AAPT: error: resource style/Theme.BaseActivity.DayNight.NoActionBar (aka three.termux.api:style/Theme.BaseActivity.DayNight.NoActionBar) not found.

     ERROR: /home/tacokoneko/code/termux/termux-generator/termux-apps-main/termux-api/app/src/main/AndroidManifest.xml:88:9-93:20: AAPT: error: resource style/Theme.BaseActivity.DayNight.NoActionBar (aka three.termux.api:style/Theme.BaseActivity.DayNight.NoActionBar) not found.

     ERROR: /home/tacokoneko/code/termux/termux-generator/termux-apps-main/termux-api/app/build/intermediates/packaged_manifests/debug/processDebugManifestForPackage/AndroidManifest.xml:183: AAPT: error: resource style/Theme.MarkdownViewActivity.DayNight (aka three.termux.api:style/Theme.MarkdownViewActivity.DayNight) not found.
```